### ISSUE TITLE
Custom PD AR's don't go on the front

### ISSUE THREAD

**Issue by AndiPoop** [CMGStudios/issue-tracker#102]
**Describe the issue you're facing**
When using a custom PD AR the weapon shows up on the back instead of the front. Standard PD guns go on the front however.
**Steps to reproduce**
Use a custom AR.
**Expected behaviour**
To show on the back
**Screenshots/Video**
https://prnt.sc/1fr9gfy
**Additional context**
N/A
**Any Texture Packs (if so list)**
NVE
**Perm ID**
169263

**Comment by alfiellds** [comment]
Hello, thank you for the report. This is not a bug but instead just a case of the weapons needing to be added to the list of guns that show on the front of the ped. 

Please provide a list of weapons to which this issue is occurring and I will forward this to the developers in order for them to change.

Many thanks.

**Comment by AndiPoop** [comment]
So far these are the only ones i'm aware of:
MK18 SOG
NSR-9
AR-15 MK4
SIG 552

**Comment by AndiPoop** [comment]
Adding onto this: 
 MK-18
Devgru EoTech HK416
Hk416LB

**Comment by rubbertoe98** [comment]
Fixed.
