### ISSUE TITLE
[Bug]: SABRE PLANE AND PILOTING

### ISSUE THREAD

**Issue by babz97** [CMGStudios/issue-tracker#1211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

while piloting in the sabre plane, you cant change altitude without damaging the plane, also when you land the breaks dont even work! so you lose all the money just by changing altitude, then when you do land you cant even stop

https://medal.tv/games/gta-v/clips/j0NBVdpuo34UfFZZU?invite=cr-MSxQekgsMjA3ODk0MDM2LA

### Expected behaviour

i dont expect to be damaged when going up or down, and also when i break the plane should stop

### Steps to reproduce

1. get a sabre plane
2. start piloting job.

### CMG User ID

390747

**Comment by Keegasity** [comment]
Hello,

Please can you send me a message via discord (keegasity)

Thanks,
Keegan

**Comment by Keegasity** [comment]
Following speaking with Pebbler on discord and obtaining the Sabre from him, below are the results of some testing.

- HA-Sabre Concept - Instantly takes damage, does not slow below 108 mph when breaking unless wheels are on the ground (Cannot slow due to plane bouncing on landing, this makes it impossible to slow the plane)
- Private Jet Gulfstream G650 - Does not pull as many G's whilst in whilst, slows to around 70mph before the engine cuts out (Once wheels touch the ground plane rapidly decreases in speed)

From testing other planes, I believe the only plane that is experiencing this issue is the HA-Sabre Concept (hasabre). This will be looked into.

Thanks for the report,
Keegan

**Comment by packfile** [comment]
This is not an issue from our end, if you accelerate too quickly in the Z axis (up/down in GTA) this will cause damage.
