### ISSUE TITLE
Can't hear anyone and people cant hear me

### ISSUE THREAD

**Issue by 5iftyyy** [CMGStudios/issue-tracker#138]
I'm not able to speak to anyone because they can't hear me and I can't hear them, I'm not sure whats wrong as I've done everythink I know to try and fix it. It doesn't show blue in their ids like I can't see them speaking, but it shows blue on shouting when I speak but they can't still hear me.

Try and reinstall fivem, Turn voicechat on and off, cleared cache, changed my headset and my mic, relogged, I have done all those.
I expect that It should work for me to hear people and speak to them by them hearing me back.

I got no video, but they people can't hear me and I can't hear them. 

People can't hear me and I can't hear them.

N/A

184065

**Comment by 5iftyyy** [comment]
I have also tried and reset my cmg settings.

**Comment by loganuk** [comment]
I hope you have been able to resolve this issue since making the report.

Unfortunately on testing I cannot produce any conditions to re-produce this as a scripting bug for the developers - It is almost certainly a client side issue.

When it comes to audio issues, there are other possibilities on your PC (i.e sound settings)

Try using #game-support on the CMG Discord to get help from others.
