### ISSUE TITLE
[Bug]: Can't sell plat days

### ISSUE THREAD

**Issue by terrorist** [CMGStudios/issue-tracker#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Cannot sell my plat days, I have 37 and it will not let me sell them but would previously.

### Expected behaviour

Expect the blue box menu to appear when I attempt to sell plat days

### Steps to reproduce

1. Type /cmgclub in the text chat
2. Press enter on manage subscription
3. Press enter on sell platinum subscription days
4. Does not appear with any box

Example: https://youtu.be/wZNqUGqpMCE

### Any Texture Packs? (If so list)

No Night or something

### CMG User ID

228308

**Comment by rubbertoe98** [comment]
Reason for closing?

**Comment by menstruated** [comment]
Discovered that it happens when you're in the cmgclub menu and another menu causes it to close. Essentially the cmgclub menu messes up. Then stops you from continuing to sell for some unknown reason. It's hard to replicate but a few staff members I've spoken to know about it and others are completely unbeknownst to the issue.

**Comment by crazychris2404** [comment]
Should be fixed after the next restart at midnight. If this issue still persists after this time please respond to this issue.

**Comment by crazychris2404** [comment]
Closed due to being linked with a pre existing issue. Linked above
