### ISSUE TITLE
[Bug]: TWITTER LINK

### ISSUE THREAD

**Issue by VenoBeatz** [CMGStudios/issue-tracker#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when trying to link to the twitter, it doesnt connect 

### Expected behaviour

cant link twitter

### Steps to reproduce

/linktwitter

### CMG User ID

229895

**Comment by crazychris2404** [comment]
Hello,
Sorry for the late response can you confirm if this issue is still occurring?
You should be able to link your twitter account using /linktwitter in game and signing in. After you have successfully linked your account i would recommend waiting around 15 minutes then doing /twitterreward and you should receive the 500k.

**Comment by crazychris2404** [comment]
If you are still getting this problem feel free to open another issue as this appears to have been fixed since you first created this report.
