### ISSUE TITLE
[Bug]: Dosen't give me verification code

### ISSUE THREAD

**Issue by Spacernest** [CMGStudios/issue-tracker#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the discord says that if you log in you see a verification code, but I don't get anything I just get loaded into the server!

### Expected behaviour

Im a dumbass and don't know what this means.

### Steps to reproduce

There are no ways to reproduce this.

### Any Texture Packs? (If so list)

nope

### CMG User ID

225740

**Comment by crazychris2404** [comment]
Hello,
Sorry for the late response if you can load into the server and do not recieve a code this means you already have a discord linked to your account and have since made a new discord account. If this has not been resolved then you will need to fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSdkBRG7AIAHIR5mz0JlDPkgYQh9hLc87yUiR3f3-j9Lwy4VUg/viewform) and someone will sort your verified status for you.
