### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BjornLothbr** [CMGStudios/issue-tracker#425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i bought a new rank well an upgraded rank i selected a new aircraft to get i bought it but it has not came threw so im asking if u can add my jet on thanks if possible u can check if i have bought it my name in game is GHM and on discord its Bjorn- thanks again hope it works.

### Expected behaviour

n/a

### Steps to reproduce

n/a

### Any Texture Packs? (If so list)

Upgrade from supreme to kingpin

### CMG User ID

280176

**Comment by Pugles-Beancat** [comment]
Hi, this is most likely due to you not owning a pilots license purchasable at City Hall, if this solution does not work for you then this is a donation error and not specific to the CMG server.

This is not a server bug and if the above remedy does not work for yourself then you need to open a donation support ticket via the discord @ https://discord.gg/BCmneFxt

**Comment by crazychris2404** [comment]
The information listed above is correct i will be closing this issue,
Any more problems feel free to reply to this issue
