### ISSUE TITLE
[Bug]: Molotov

### ISSUE THREAD

**Issue by kajblm** [CMGStudios/issue-tracker#487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you buy the Molotov item form VIP island you can throw it but it doesnt show on other players screens nor does it deal any damage. Basically has no use.

### Expected behaviour

It should damage the player in the area you threw it.

### Steps to reproduce

1. Buy Molotov
2. Throw it
3. You will see it doesn’t do damage or anything.

### Any Texture Packs? (If so list)

N/A

### CMG User ID

214124

**Comment by crazychris2404** [comment]
This is caused due to it being client sided I will speak to the developers and find out if this is intentional

**Comment by crazychris2404** [comment]
After speaking to developers I have been informed that this is not intentional and would also like to add that other things such as the gas barrels inside of the prison are also client sided and only have a affect when blown up. This is issue will be moved to low priority due to not currently having a a major affect on the server

**Comment by kajblm** [comment]
Will it ever be the case that we can use the properly as throwing Molotovs would make for some great roleplay.

**Comment by packfile** [comment]
Thanks for the report, this has been fixed
