### ISSUE TITLE
[Bug]: Turf capturing bug

### ISSUE THREAD

**Issue by Evextt** [CMGStudios/issue-tracker#610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I had LSD north turf and someone started capturing it and ended up taking it from me. I went there killed them all and tried to capture it back but it said i already owned the turf even though in the f5 turf menu it said i didnt. Ive seen it happen before with large arms aswell

### Expected behaviour

I had LSD north turf and someone started capturing it and ended up taking it from me. I went there killed them all and tried to capture it back but it said i already owned the turf even though in the f5 turf menu it said i didnt. Ive seen it happen before with large arms aswell

### Steps to reproduce

I had LSD north turf and someone started capturing it and ended up taking it from me. I went there killed them all and tried to capture it back but it said i already owned the turf even though in the f5 turf menu it said i didnt. Ive seen it happen before with large arms aswell

### Any Texture Packs? (If so list)

none

### CMG User ID

929

**Comment by crazychris2404** [comment]
Hi @Evextt 
Thanks for the report
Do you have a clip of this occuring?

**Comment by packfile** [comment]
This does not reproduce locally. The following scenarios have been tested and provide correct results.

First Scenario:
1) Gang A captures LSD North turf.
2) Gang B attempts to capture LSD North turf off of Gang A.
3) Gang A kills all of Gang B members.
4) Gang B fails to capture and Gang A retains the turf.

Second Scenario:
1. Gang A captures LSD North turf.
2. Gang B attempts to capture LSD North turf off of Gang A.
3. Gang B successfully captures LSD North turf from Gang A.
4. Gang A attempts to cature LSD North turf off Gang B.
5. Gang A kills of all Gang B members.
6. Gang A successfully captures  LSD North turf off Gang B.

Since the requested clip hasn't been provided in 2+ weeks the issue will be closed.
