### ISSUE TITLE
[Bug]: Cannot access my gang funds or make a gang or join another gang. 

### ISSUE THREAD

**Issue by PHM4** [CMGStudios/issue-tracker#693]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Cannot access my gang funds or make a gang or join another gang. I just keep getting errors. Not sure what is happening. I have the gang license.

When i try to join my mates gang they get a error that im already in a gang. 

https://tinyurl.com/gangfunds

If that expires:

https://youtu.be/KwJfh4il6LY

### Expected behaviour

Lost a lot of money that took my forever to grind and now lost, as it was in gang funds now i cannot access anything.  

### Steps to reproduce

Press F5
Press Create Gang
Type in the name
Press enter

### Any Texture Packs? (If so list)

No

### CMG User ID

209490

**Comment by crazychris2404** [comment]
This has already been resolved for you i believe.
Can you please confirm

**Comment by tom-gun** [comment]
Unfortunately since you have failed to provide info how to cause this it can't be fixed. _"Lost a lot of money that took my forever to grind and now lost, as it was in gang funds now i cannot access anything."_, is an exaggeration and seems more like a rant than trying to help. When you're prepared to open constructive dialog this can be looked in to.
