### ISSUE TITLE
NHS Volvo V70

### ISSUE THREAD

**Issue by JamieGarner** [CMGStudios/issue-tracker#70]
**Describe the issue you're facing**
When you attempt to turn the ELS on with Q it opens the radio wheel, the only way to turn the ELS on is through pressing E which doesn't turn on all the lights and removes the option of switching siren modes.

**Steps to reproduce**
Become an Paramedic, go to the Garage outside of St Thomas Hospital and spawn the NHS Volvo V70 and press Q or E.

**Expected behaviour**
Pressing Q should turn the ELS on but opens the radio wheel.

**Screenshots/Video**
N/A

**Additional context**
N/A

**Any Texture Packs (if so list)**
N/A

**Perm ID**
151659

**Comment by alfiellds** [comment]
Hello JamieGarner, thank you for the report.

Could you answer the following questions please, in order to help the developers determine the issue:

- Does this issue occur with other NHS vehicles?
- Have you tried relogging? (if not try this and then try the "Q" ELS on the NHS Volvo V70).

Many thanks.

**Comment by alfiellds** [comment]
Closing this due to failure to provide the needed information.

If this issue occurs again, please clip it and open a new bug report, providing the video.
