### ISSUE TITLE
[Bug]: Cant link twitter account for 500k bonus

### ISSUE THREAD

**Issue by bouldurz1** [CMGStudios/issue-tracker#720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

whenever i do /linktwitter it takes me to a site and says internal error so i cannot link my twitter

### Expected behaviour

Cant link my twitter

### Steps to reproduce

1.follow cmgfivem
2./twitterreward
3.error

### CMG User ID

339287

**Comment by PIKAlmao** [comment]
The link twitter system isn't really working due to how limited the api system is, it only allows a certain amount of uses per day which is 20 or something from what i've heard, so they usually get used instantly, might be worth having a try right after midnight or after the daily 10am restart, i'm not 100% sure on when the api gets refreshed.

**Comment by crazychris2404** [comment]
Thanks @PIKAlmao for providing the correct information 

issue closed
