### ISSUE TITLE
Camper 5 sandy shores bugged.

### ISSUE THREAD

**Issue by RobbieIsGeenZweed** [CMGStudios/issue-tracker#73]
**Describe the issue you're facing**
I bought yesterday an house in sandy shores. It's called sandy caravan 5. The problem is that I can't get in my house anymore, I can only ring bell etc.

**Screenshot**
![image](https://user-images.githubusercontent.com/87441226/125664806-839ff6b1-a8bb-464b-bb74-b4d73bec8939.png)
![image](https://user-images.githubusercontent.com/87441226/125664977-b61ed894-6b91-49e6-8f94-d71dfbe91bbf.png)

**Perm ID**
146434

**Comment by alfiellds** [comment]
Hello, this issue is occurring as you do not own the property. If you have attempted to purchase the property and have been charged but have not received the property, please open a compensation request at the link below and provide the information which the form requests. A senior member of staff will review this and compensate you if necessary.

https://cmgforums.com/forums/index.php?/forms/2-comp-request/

Many thanks.
